### ISSUE TITLE
Facebook login/signup not linking to existing users registered via Parse login/signup

### ISSUE THREAD

**Issue by raydenx** [ParsePlatform/ParseUI-Android#10]
If the app is using both Parse login and Facebook login user can register first using Parse login and then again using Facebook login. These two accounts should be linked if email address is the same. Especially, when PARSE_LOGIN_EMAIL_AS_USERNAME is set to true.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
