### ISSUE TITLE
res/values-ko/strings.xml in ParseUI-Login

### ISSUE THREAD

**Issue by usualCoder** [ParsePlatform/ParseUI-Android#105]
Hi. I am a usual-novice-beginner to github so apology in advance.

I want to contribute to the source but I don't know fully about github so I upload file thru here.

I have translate the strings.xml in ParseUI-Login project to Korean(ko-KR).
Only the user-interfaced part was translated.

I don't care about copyright. my source(?) part is public domain and fully free to use.
please somebody transfer it to source

Thanks for dev such easy to use SDK. keep up the good work.

thanks!
[strings.xml.zip](https://github.com/ParsePlatform/ParseUI-Android/files/55137/strings.xml.zip)

**Comment by wangmengyan95** [comment]
I make a pull request for this #106. @usualCoder could you double check that. Thanks for your contribution!

**Comment by usualCoder** [comment]
yes I checked it and seems all is well. Thanks for your helping!
