### ISSUE TITLE
error non java :(

### ISSUE THREAD

**Issue by Jason1994100** [ParsePlatform/ParseUI-Android#113]
hii i got some problem with the apps.. 
(Error:Execution failed for task ':example_app:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_65\bin\java.exe'' finished with non-zero exit value 2)
can u help me with this? :(

this is the grade file

apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion '23.0.2'

    defaultConfig {
        applicationId "io.particle.cloudsdk.example_app"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    packagingOptions {
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/maven/org.kaazing/gateway.client.java.transport/pom.xml'
        exclude 'META-INF/maven/org.kaazing/gateway.client.java.transport/pom.properties'
        exclude 'META-INF/maven/org.kaazing/net.api/pom.xml'
        exclude 'META-INF/maven/org.kaazing/net.api/pom.properties'
    }

}

dependencies {
    compile 'com.nineoldandroids:library:2.4.0'

    // BY DEFAULT, BUILD APP AGAINST THE LOCAL SDK SOURCE
    // (i.e.: make modifications to the SDK source in the local repo show up in this app
    // just by rebuilding)
    compile project(':cloudsdk')
    //
    // **OR**
    //
    // comment out the above, and
    // UNCOMMENT THE FOLLOWING TO USE A PUBLISHED VERSION OF THE SDK:
    //    compile 'io.particle:cloudsdk:0.1.2'

    compile 'org.apache.commons:commons-lang3:3.3.2'
    compile 'com.google.code.gson:gson:2.3.1'
    compile 'com.google.guava:guava:18.0'
    compile 'com.squareup.okhttp:okhttp:2.5.0'
    compile 'com.squareup.okio:okio:1.6.0'
    compile 'com.squareup.retrofit:retrofit:1.9.0'

    compile 'com.android.support:appcompat-v7:23.1.1'
    compile 'com.android.support:support-v4:23.1.1'
}

**Comment by wangmengyan95** [comment]
Hi @Jason1994100, I do not see any Parse related dependencies in your gradle file. Are you sure you open the issue in the right repo?
