### ISSUE TITLE
Error:(124, 20) error: incompatible types: Context cannot be converted to Activity

### ISSUE THREAD

**Issue by mishrakrishnakant** [ParsePlatform/ParseUI-Android#116]
So I am getting the above error which clearly has to do with the fact that this is a fragment and not an activity but I am not sure why though.

These are the lines of code where there is the error

    @Override
    public void onAttach(Context context) {
      super.onAttach(context);

I have no idea what is wrong where, the rest of the code works perfectly fine. The error is in ParseLoginFragment.java

**Comment by lems111** [comment]
Hello, 
Looking at your sample code,  I don't see how you would get that error; but,  I can tell you that when I use that override function to register my activity as a listener, it doesn't work. There is a deprecated version of this function that I still use to get around that problem which passes the activity object that I can cast as my listener object.

**Comment by mishrakrishnakant** [comment]
The override was there by default. I removed it and cleaned it 2-3 times, (I don't know why that was required) but it worked so thanks for the help.

**Comment by tcx02** [comment]
i have the same issues but tried to delete the ovveride but the problem is still there
![image](https://user-images.githubusercontent.com/103909886/183287236-ec5061d9-cb75-4ba0-8ad7-e4550cfb23f0.png)
