### ISSUE TITLE
ParseQueryAdapter for RecyclerView

### ISSUE THREAD

**Issue by msrowley** [ParsePlatform/ParseUI-Android#127]
I opened this issue a long time ago, but you marked it as closed without providing a solution. I asked for permission to open it again, but got no answer from you, which is unacceptable for a serious company support. Anyway, I have to report it again, in case someone more responsible lay an eye upon it and at least be able to provide a reply or guide me to a proper support address.

When will ParseQueryAdapter  be compatible for RecyclerView??

This should be a priority for the parse sdk, as for any app that wants to support the material design principles and widgets and be backwards compatible with older versions of android, it is a necessity to use the recycler view widget from the support library, something that parsequeryadapter doesn't support until today. I really cannot understand why it is not implemented yet. Are you aware of the latest android development news?? RecyclerView is out for at least one and a half year and the design support and AppCompat libraries which support the material design guidelines are at least out for half a year. As I stated in my op, Google suggests migration to RecyclerView not only for Lollipop(and now Marshmallow) , but for older versions too!! I would like to hear from you please.

And please, do not mark it again as closed before at least answering on that matter, if you want to call yourself a serious company.

I tried a lot of times with the polite way :-1:

**Comment by msrowley** [comment]
@wangmengyan95 are you trolling or you just trying to build a worse reputation for the company you are working with?? In the previous thread you personally said that you will look into that matter, and you haven't even answered since yet... Is there an explanation of this unacceptable behavior of yours or you are just being childish??

**Comment by grantland** [comment]
I've been working on it, but have had other responsibilities that have higher priority. It will be released soon, but probably not in the manner you'd expect.

**Comment by grantland** [comment]
Please refer to #128

**Comment by msrowley** [comment]
@grantland Thank you very much for your kind reply and for sharing some info on this matter. It's sad that parse closes its doors though!! Wish you good luck!!
