### ISSUE TITLE
Cannot use it along with the Parse SDK

### ISSUE THREAD

**Issue by rojymoon** [ParsePlatform/ParseUI-Android#13]
In my project I'm using the Parse SDK and now i want to add the Parse Login UI .. I've imported the ParseUI into my eclipse but i cannot use it inside my project, it gives me this error [Jar mismatch! Fix your dependencies] everytime i tried to include it as a library to my project. 

Any help!

**Comment by jegesh** [comment]
You can delete the parse.jar in the main project, but not in the login library. That we just give you loads of errors.
