### ISSUE TITLE
Intent data is not passed along to target activity

### ISSUE THREAD

**Issue by vishalpatel** [ParsePlatform/ParseUI-Android#15]
I found that in ParseLoginDispatchActivity we drop the intent args passed by requestor. I breaks some workflows where the requestor has set args for profile activity to show user profile by arg (say "email") and then because of the loginDispatchActivity the args are lost.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.
