### ISSUE TITLE
Question about installing

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/ParseUI-Android#23]
Hello!
I'm trying to use this lib but I have a question regarding the installation.
I see that the point 2 says: "Import this repository's project with Android Studio (File > Import Project > ParseUI-Android folder). The project has Maven dependencies on the Facebook SDK and the Bolts framework. Android Studio automatically resolves these via Gradle."
It says that facebook and bolts libreries are installed automatically. What I don't understand is, what about the Parse library? When is installed? Is it embedded inside ParseUI library?
Thanks.

**Comment by stanleyw** [comment]
The Parse library is in the ParseLoginUI/libs folder of this project.

**Comment by Ricardo1980** [comment]
Does that mean I can use gradle to install Parse remotely? (Without manually downloading the jar file)
Thanks. 

Enviado desde mi iPhone.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hello @Ricardo1980, recently we open source our SDK and publish it to Maven. Check #57 and the instruction in our open source repo [Parse](https://github.com/ParsePlatform/Parse-SDK-Android).
