### ISSUE TITLE
IllegalArgumentException when opening new user

### ISSUE THREAD

**Issue by jegesh** [ParsePlatform/ParseUI-Android#27]
I've seen that a few other people online had this problem, but I didn't find any solutions.  Using the UI library, the ParseSignupFragment class causes an error (IllegalArgumentException) on line 174, when it first initializes the ParseUser class, and it claims the class was not registered as a ParseObject subclass.  Yes, this sounds ridiculous, and I must've changed something because I was able to signup one user before I started getting this error, but there it is.  I tried changing the project settings, but to no avail.

**Comment by stanleyw** [comment]
Do you get the same exception when running the sample apps in this repo?  What version of Android are you running on?

**Comment by jegesh** [comment]
Let me try a sample app and I'll get back to you.
Android 5.0.1.
Strangely enough, it did work for me at some point, and I can't for the life of me figure out what I could have changed to cause this.

**Comment by jegesh** [comment]
The sample app worked fine.

**Comment by jegesh** [comment]
Okay, I finally figured it out.  I was registering a ParseUser subclass, which was overriding the `_User` classname and causing all sorts of problems.
