### ISSUE TITLE
Publish Parse Library to jCenter and/or MavenCentral

### ISSUE THREAD

**Issue by jaredsburrows** [ParsePlatform/ParseUI-Android#28]
I am not sure why you guys have not published this library to `jCenter` or `MavenCentral`, is there a real reason for that?

Instead of having to download a .jar and then use it as a local dependency:

    dependencies {
        compile files('libs/Parse-1.8.2.jar')
    }

We should be able to simply include it as a maven dependency:

    dependencies {
        compile 'com.parse:android:1.8.2'
    }

My suggestion would be to publish to Jcenter and sync with MavenCentral. Do you need help setting it up?

**Comment by akhyrul** [comment]
+1 

Just getting started with Parse, and this issue already irritates me. I just don't really like putting *.jar dependencies in my git repository.

**Comment by stanleyw** [comment]
Thanks for your feedback.  MavenCentral requires that the library be open source, but currently Parse.jar is not open source.  I'll update the README to reflect your feedback.

**Comment by jaredsburrows** [comment]
It would take seconds to "open source" Parse and/or simply decompile it.

This repository can at least be put on JCenter.

**Comment by SemonCat** [comment]
Is any possible to open source parse.jar?

**Comment by jaredsburrows** [comment]
@SemonCat Either they do not care to respond or simply won't do it. You can just easily download: http://jd.benow.ca and decompile it.

**Comment by thedamfr** [comment]
You could have your own public repo. It's what does proprietary but developer-friendly tools like Bugsense or Fabric does.

**Comment by jitpack-io** [comment]
Also it's easy to publish using JitPack. In fact, it's already there: https://jitpack.io/#ParsePlatform/ParseUI-Android/82caece93e and usable as a Maven/Gradle dependency : )

Would be slightly easier if there was a GitHub release though.

**Comment by albertvilacalvo** [comment]
+1 We have to download the jar every time you update it!

**Comment by joaocsousa** [comment]
:+1: please do this!

**Comment by yongjhih** [comment]
Via 8tory/parse-android-sdk.m2:

```gradle
repositories {
    maven { url 'https://github.com/8tory/parse-android-sdk.m2/raw/master/' }
}

dependencies {
    compile 'com.infstory:parse:1.9.2'
    compile 'com.infstory:parse-crash-reporting:1.9.2'
    compile 'com.infstory:parse-facebook-v3:1.9.2'

    compile 'com.facebook.android:facebook-android-sdk:3.20.0'
    compile 'com.parse.bolts:bolts-android:1.1.4'
}
```

or via jitpack.io / yongjhih/parse, yongjhih/parse-crash-reporting, yongjhih/parse-facebook-v4

```gradle
repositories {
    maven {
        url "https://jitpack.io"
    }
}

dependencies {
    compile 'com.github.yongjhih:parse:1.9.2'
    compile 'com.github.yongjhih:parse-crash-reporting:1.9.2'
    compile 'com.github.yongjhih:parse-facebook-v3:1.9.2'

    compile 'com.facebook.android:facebook-android-sdk:3.20.0'
    compile 'com.parse.bolts:bolts-android:1.1.4'
}
```

**Comment by jaredsburrows** [comment]
@yongjhih Very nice!

**Comment by LOG-TAG** [comment]
now 1.9.3 is the latest one!! I'm lazy or parse guys!! :) why don't they  published this library to jCenter or MavenCentral!!

**Comment by jaredsburrows** [comment]
@LOG-TAG Look at @yongjhih 's suggestion. Also, I believe I have seen you on StackOverflow before.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by grantland** [comment]
Since we're [open source](https://github.com/ParsePlatform/Parse-SDK-Android) now, it's on [Maven Central](http://search.maven.org/#search|ga|1|g:"com.parse" AND a:"parse-android") :)

```java
dependencies {
    compile 'com.parse:android:1.10.0'
}
```

**Comment by yongjhih** [comment]
Thanks, it's good news. I think I could deprecate my parse maven packages on github, jitpack and jcenter.

**Comment by yongjhih** [comment]
Thanks, it's good news. I think I could deprecate my parse maven packages on github, jitpack and jcenter.

**Comment by albertvilacalvo** [comment]
@grantland Should be `compile 'com.parse:parse-android:1.10.0'` instead of `compile 'com.parse:android:1.10.0'`.

**Comment by grantland** [comment]
@albertvilacalvo thanks! fixed.

**Comment by wangmengyan95** [comment]
#57

**Comment by grennis** [comment]
Will it be possible to add the Parse Facebook and Twitter utils libraries to maven as well?

**Comment by albertvilacalvo** [comment]
+1 Publishing the ParseFacebookUtils and ParseUI to maven!

**Comment by Ralphilius** [comment]
@wangmengyan95 Does this ticket mean to add ParseUI into jCenter and/or MavenCentral?

**Comment by jaredsburrows** [comment]
@wangmengyan95  @Ralphilius Yes

**Comment by wangmengyan95** [comment]
@Ralphilius , yes, I am working on that. Since we open source Parse, I need to do some clean up before we add to MavenCentral.

**Comment by StingerAJ** [comment]
Any news on Parse UI on Maven Central or JCenter?

**Comment by wangmengyan95** [comment]
@StingerAJ  Pretty close, after we land #66 , we are good to go. Since #66 is a breaking change, we want to open it for a while for suggestions, recommendations from developers.

**Comment by Bodo1981** [comment]
@wangmengyan95 Issue #66 is closed. So are there any news about releasing Parse-UI to maven central?

**Comment by cprcrack** [comment]
Please publish ParseCrashReporting to maven also!

**Comment by wangmengyan95** [comment]
Done, we just publish to Maven. Check README.md about how to import it.
