### ISSUE TITLE
readme.md "running sample apps"

### ISSUE THREAD

**Issue by rowntreerob** [ParsePlatform/ParseUI-Android#31]
good as far as it goes but it really needs the following added that covers Parse Dashboard....

When you have set up the Facebook app over at "developers.facebook.com/apps" in the facebook console , you will have access to the following:

AppId, App Secret  ( 2 values from FB that need to be plugged into Parse.com dashboard as follows:

go to Parse dashboard for the parse App 

go to  settings / authentication /  allow FB auth  , mark to YES

go to  settings / authentication / Facebook Applications and fill in the Appid , Secret values and  enter.

Until you do this stuff you just get exception: com.parse.ParseException: Unacceptable Facebook application id.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hello @rowntreerob, thanks for you suggestion. I will add this to our readme.md

**Comment by wangmengyan95** [comment]
Added to the new wiki.
