### ISSUE TITLE
android.content.res.Resources$NotFoundException

### ISSUE THREAD

**Issue by timtianyang** [ParsePlatform/ParseUI-Android#33]
Some devices generate this error:

android.content.res.Resources$NotFoundException: Resource ID #0x7f0202e8 at android.content.res.Resources.getValue(Resources.java:2333) at android.content.res.Resources.startRC(Resources.java:1059) at android.app.ActivityThread$mRunnable.run(ActivityThread.java:2476) at java.lang.Thread.run(Thread.java:818)

After camera finishes taking a picture, the image cropping activity doesn't start up. I did some checking on bitmap and it looks like inside this function:
private Bitmap getBitmap(String path);
generates an exception. 
Even I put setResult(RESULT_CANCELED); finish(); to safely exit, the main activity was restarted.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hi @timtianyang , ParseUI does not provide any functionalities related to camera and image processing. Are you sure the issue you mentioned is related to ParseUI? If so, could you please provide some code snippets or a sample project to repo this issue?

**Comment by wangmengyan95** [comment]
I will close this due to no necessary response. Feel free to re-open it.
