### ISSUE TITLE
Fail to login with facebook

### ISSUE THREAD

**Issue by cyberrob** [ParsePlatform/ParseUI-Android#34]
have anyone experience this?

04-01 18:37:10.671  21417-21417/com.parse.loginsample.basic W/ParseLoginFragment﹕ Facebook login failed, exception: com.parse.ParseException: Invalid date

not sure why this happen.

**Comment by cyberrob** [comment]
it show error code 107 with invalid date. But it didn't send any date...

**Comment by amiraelsayed** [comment]
hello Robert,

I am facing the same problem, did you find the solution ??

**Comment by stanleyw** [comment]
Could you guys follow this bug, and try to provide more precise repro steps on the bug?  Thanks! https://developers.facebook.com/bugs/988782637800413/

**Comment by cyberrob** [comment]
Here's what I've done.

1. Clone the repo.
2. Import entire repo into Android Studio.
3. Change `parse_app_id`, `parse_client_key`, `facebook_app_id` to my own settings.
4. Compile & run it.
5. Click `Facebook Login`.
6. Enter email & pwd into the Single-Sign-On web page.
7. The dialog said I've authorized the app and click `done`.
8. It show `facebook login failed`: 04-26 23:11:56.625  28542-28542/com.parse.loginsample.basic W/ParseLoginFragment﹕ Facebook login failed, exception: com.parse.ParseRequest$ParseRequestException: Invalid date

First install and run will show the toast said login failed, but after that it won't show any toast. And here's some error logs every time I try to login with facebook:

04-26 23:19:11.112  30336-30395/com.parse.loginsample.basic E/ActivityThread﹕ Failed to find provider info for com.facebook.katana.provider.AttributionIdProvider
04-26 23:19:11.211  30336-30336/com.parse.loginsample.basic E/ActivityThread﹕ Failed to find provider info for com.facebook.katana.provider.PlatformProvider
04-26 23:19:11.212  30336-30336/com.parse.loginsample.basic E/ActivityThread﹕ Failed to find provider info for com.facebook.wakizashi.provider.PlatformProvider

**Comment by cyberrob** [comment]
even the sample app can't login with facebook... don't mention that imported into my project..

**Comment by cyberrob** [comment]
@stanleyw could you take a look of this issue? I've updated to 1.9.1 and Facebook v4.0 but the issue still occur.

**Comment by cyberrob** [comment]
I've solved the problem by deleting the app in my facebook account, also uninstall the app on the device to start fresh. And it worked! Close it now.
