### ISSUE TITLE
proguard

### ISSUE THREAD

**Issue by rowntreerob** [ParsePlatform/ParseUI-Android#39]
has anyone done a release with version 4?

i upgraded the lib, tested ... all fine until i tried to do a release and proguard failed on dupe zip entries in package com.parse..

detls: 
Execution failed for task ':proguardRelease'.
 java.io.IOException: Can't write /home/rob/src/CastVideos-android/build/intermediates/classes-proguard/release/classes.jar] (Can't read [/home/rob/src/CastVideos-android/build/intermediates/exploded-aar/CastVideos-android/ParseLoginUI/unspecified/libs/Parse-1.9.1.jar(;;;;;;!META-INF/MANIFEST.MF) (Duplicate zip entry Parse-1.9.1.jar:com/parse/AnonymousAuthenticationProvider.class))

re: http://stackoverflow.com/questions/29870207/proguard-dupe-zip-entry-after-upgraded-facebook-parse-ui-lib-to-v4

**Comment by rowntreerob** [comment]
IMO instructions below (build.gradle) are not right for proguard: 

    // Your project's build.gradle should say:
    //
    //     compile files('YOUR_PROJECT_LIBS_PATH/Parse-1.9.1.jar')
    //     compile files('YOUR_PROJECT_LIBS_PATH/ParseFacebookUtilsV4-1.9.1.jar')

Those 2 lines in the "project.root.build.gradle" are causing the proguard dupe zip error. 
Commenting out those 2 lines solves the proguard issue.

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Since we have open source Parse SDK, you do not need to import the local jar to build your app. Not sure this is still a valid issue, feel free to reopen it.
