### ISSUE TITLE
How to logout from Facebook?

### ISSUE THREAD

**Issue by eloudsa** [ParsePlatform/ParseUI-Android#40]
Hi

Using ParseUI eases the way to log on Parse, FB or Twitter.

But ...

While it's obvious how to logout from Parse (PFUser.logout()), it's not so straightforward how to apply the same process on FB.
When I logout, we go back to the login activity. 
But if I click on the "Log in with Facebook" button, my app gives me the access without any credential and stay locked to the previous logged out user.

Do you any tips to share in order to implement a FB logout ?

Thanks for your help.

Said

**Comment by facebook-github-bot-9** [comment]
Thank you for reporting this issue and appreciate your patience. We've  notified the core team for an update on this issue. We're looking for a response within the next 30 days or the issue may be closed.

**Comment by wangmengyan95** [comment]
Hi @eloudsa , for Parse, we just ask Facebook SDK to give us user's credential. If you want to complete logout from Facebook, you have to call Facebook SDK or change the Facebook setting to do this. There is noting we can do from Parse side.
