### ISSUE TITLE
How can I remove NAME field in signup UI?

### ISSUE THREAD

**Issue by Ricardo1980** [ParsePlatform/ParseUI-Android#43]
Hello!

I customized the signup user interface (com_parse_ui_parse_signup_form.xml) and I removed 
"android:id="@+id/signup_name_input" because I don't want to save user's name. We already save username, email and password, so (long) name is useless in my system.

It seems it's supported by code as seen here in ParseSignupFragment.java:

    if (nameField != null) {
      name = nameField.getText().toString();
    }
// Set additional custom fields only if the user filled it out
      if (name.length() != 0) {
        user.put(USER_OBJECT_NAME_FIELD, name);
      }

But my app crashes with this message:

    Process: com.ricardoruizlopez.sharewifi, PID: 12112
    java.lang.NoSuchFieldError: No static field signup_name_input of type I in class Lcom/parse/ui/R$id; or its superclasses (declaration of 'com.parse.ui.R$id' appears in /data/app/com.ricardoruizlopez.sharewifi-1/base.apk)
            at com.parse.ui.ParseSignupFragment.onCreateView(ParseSignupFragment.java:93)

It seems this line:
nameField = (EditText) v.findViewById(R.id.signup_name_input);
from file:
ParseSignupFragment.java
is failing.
But, why? if that EditText is not available, I guess that value should be null.

Any idea?

**Comment by wangbourne** [comment]
+1, better to have a similar function like "setParseSignupName(false)" to facilitate

**Comment by wangbourne** [comment]
I tried this function by introducing

compile 'com.parse:parseui-login-android:0.0.1'
compile 'com.parse:parseui-widget-android:0.0.1'

The name field is still there. Is it because you haven't update these two?
