### ISSUE TITLE
Parse Login Facebook Failed after logout

### ISSUE THREAD

**Issue by noodlebbb1010** [ParsePlatform/ParseUI-Android#46]
I am able to login with facebook account and do authentications at the first time..
but when I click logout and click login with facebook again.. the message "Facebook login failed" keeps prompting.. I tried uninstall and reinstall the app but it doesn't work.. 

I have been looking at the Parse library class but cant figure out whats going wrong .. 
Please help!!

**Comment by wangmengyan95** [comment]
Hello @noodlebbb1010 , I just tried with the sample and it worked fine. Could you provide more details about the error, like stack trace, log etc? Thanks.

**Comment by yadav304** [comment]
I have the same problem.. when i remove the app from background task and relaunch its working but as soon as i logout and try to login it doesn't.. SampleDispatchActivity is working fine but I used the same code it's not working..

**Comment by wangmengyan95** [comment]
@deepakbharanikana , since I can not repo this bug, is it possible for you to provide your sample project or some code snippets to us for debug?

**Comment by wangmengyan95** [comment]
I will close this due to no necessary response. Feel free to re-open it.
