### ISSUE TITLE
The unicity of email should be checked before inserting the user record in Parse using the Facebook email

### ISSUE THREAD

**Issue by prempena** [ParsePlatform/ParseUI-Android#49]
The user email must be unique in Parse. When a new Facebook user is signing up, the user object is inserted in Parse with an empty email. When trying later to populate the email field using the Facebook API GraphRequest, the updated email may already exists in Parse.

=>The unicity of email should be checked before inserting the user record in Parse using the Facebook email.

**Comment by wangmengyan95** [comment]
@prempena thanks for opening this issue. I am sorry but I am afraid I do not fully understand your question. By my understanding, the problem is after you populate the email field using the Facebook API GraphRequest, you find the email address has already been used in Parse, so you can not register a ParseUser with this email anymore, is that correct?

**Comment by prempena** [comment]
Exactly and, moreover, why not refuse immediately the facebook user 
creation when the email address (that must be unique in Parse) is 
already used ?
Thanks,

Pascal

**Comment by grantland** [comment]
The Facebook user's email is not required to authenticate and not always requested by the developer, so we can't have this functionality in our default implementation, but you may add it to your own implementation.

**Comment by prempena** [comment]
I understand but if the mail is required and if this email already 
exists for another users, it is too late, as the Facebook user record is 
already inserted in the Parse database.

**Comment by Ralphilius** [comment]
@grantland Is there anyway we can interfere the callback by ParseUI Login?

**Comment by grantland** [comment]
Which callback are you referring to?

**Comment by Ralphilius** [comment]
@grantland Facebook Login callback. I want to check existing user before submitting to creation

**Comment by grantland** [comment]
That is not currently supported

**Comment by isramartinez** [comment]
Hey @grantland , any update on this? we are starting to build our app and we are relying on Parse-UI for the login/signup but with the auto linking or a callback to implement this by ourselves we may need to stop using parse-ui. I guess there are more people like us that would like to have the option to do that. Thanks!

**Comment by Ralphilius** [comment]
@isramartinez Can we use beforeSave cloud code here? It's just a rough idea since I have not tried it yet.

**Comment by isramartinez** [comment]
@Ralphilius yep I just tried that and actually we can do that. Here is the code sample that is working for me. Is just checking that can contact the FB Graph API and is returning data so the logic to check if there is an user with that email already and the authData to that user.

```javascript
Parse.Cloud.beforeSave(Parse.User, function(request, response) {
  if(request.object.get("authData")){
    Parse.Cloud.httpRequest({
      url: "https://graph.facebook.com/v2.5/" +
        request.object.get("authData").facebook.id + 
        "?fields=email&access_token=" + 
        request.object.get("authData").facebook.access_token,
      success:function(httpResponse){
        console.log(httpResponse.data.email);
        return response.success();
      },
      error: function(error){
        return response.error();
      }});
  }else{
    response.success();
  }
});
```

**Comment by Ralphilius** [comment]
@isramartinez Thanks for sharing your code. That covers essential part needed to process later.

**Comment by isramartinez** [comment]
I've been trying to find a workaround for this using the beforeSave but can't find the way to do it. This is as far as I've been able to get after hundreds tests, and still not working. I can't call user.save() on a beforeSave event so the only way to trigger the authData update for the previous user is calling response.success() which at the same time trigger the saving of the new user... There may be another way of doing it but I just can't find it. Debugging cloud code is not funny.

```javascript
Parse.Cloud.beforeSave(Parse.User, function(request, response) {
  Parse.Cloud.useMasterKey();
  if(request.object.get("authData") && request.object.get("email") == undefined){
    Parse.Cloud.httpRequest({
      url: "https://graph.facebook.com/v2.5/" +
        request.object.get("authData").facebook.id + 
        "?fields=email&access_token=" + 
        request.object.get("authData").facebook.access_token,
      success:function(httpResponse){
        var queryUser = new Parse.Query(Parse.User);
        queryUser.equalTo("email", httpResponse.data.email);
        queryUser.first({
          success: function(user){
            if(user){
              user.set("authData", request.object.get("authData"));
              return response.success();
            }
          }, error:function(error){
            return response.error();
          }
        });
      },
      error: function(error){
        return response.error();
      }
    });
  }else{
    response.success();
  }
});
```

I'm thinking now on redirecting the user coming from the FB login to an activity where I can check if already exists an user with the same email, update the previous record of the user with the authData from the FB user and then force a logout to immediately login again using the previous user record now updated... though I don't know if this should work...

**Comment by wangmengyan95** [comment]
@Ralphilius, exposing callback does not help for this case. Sicne when the callback gets triggered, the ParseUser has already been created. You can see the callback we use for ParseUI [here](https://github.com/ParsePlatform/ParseUI-Android/blob/master/ParseUI-Login/src/main/java/com/parse/ui/ParseLoginFragment.java#L241).
@isramartinez, why you can not call I can't user.save() in your cloud function, any exceptions or errors you get?
