### ISSUE TITLE
ParseQueryAdapter for RecyclerView 

### ISSUE THREAD

**Issue by msrowley** [ParsePlatform/ParseUI-Android#58]
When parsequeryadapter will be compatible with recyclerview as of now it is only compatible with listview. Official android documentation suggests that we migrate to recyclerview and for some lollipop APIs to work we need recyclerview.

**Comment by wangmengyan95** [comment]
@msrowley thanks for opening this issue again. We don't have immediately plan for this feature but we will definitely do it in the future. Please keep an eye on this issue. I will update the status once we start to work on it.

**Comment by Ralphilius** [comment]
Hello,

I found a gist by @ameron32 which adds support for RecyclerView. I am not sure if his approach is good but I am using it without any issue so far.

https://gist.github.com/ameron32/34329dbd5856bf5ea7c3

**Comment by wangmengyan95** [comment]
@Ralphilius Thanks for the resource, we will take a look and try to add it to our repo as soon as possible. Since it works for you right now, I will close this issue. Feel free to re-open it if you have any questions.

**Comment by msrowley** [comment]
@Ralphilius Thank you very much for the info. I am trying to use this into my project, but I cannot understand where and if I should use the ViewHolder, onBindViewHolder(), and onCreateViewHolder methods that are required from recyclerview. Would it be easy for you to share some code to understand how I should use this gist as it is crucial for my app. Thank you again for your time!!

**Comment by Ralphilius** [comment]
@msrowley If you notice that there are 3 possible Constructors. The 1st one is more adaptive. Let's say I am creating ParseGridAdapter. The code is:


    public class ParseGridAdapter extends ParseRecyclerQueryAdapter<MyCustomModel, ParseGridAdapter.ViewHolder>{

    public ParseGridAdapter(ParseQueryAdapter.QueryFactory<MyCustomModel> factory, boolean hasStableIds) {
        super(factory, hasStableIds);
        //Your other code here
    }
    
Then you just need to do normally as with Recycler adapter.

factory can be obtained with below code or you just need to pass in your classname when declaring your adapter.

        ParseQueryAdapter.QueryFactory<YourCustomModel> factory = new ParseQueryAdapter.QueryFactory<YourCustomModel>() {
            @Override
            public ParseQuery<YourCustomModel> create() {
                ParseQuery<YourCustomModel> query = ParseWallpaper.getQuery();
               //Your other code here
                return query;
            }
        };

**Comment by msrowley** [comment]
@Ralphilius Thank you very much for your lightning fast reply. So to make things clear for me, I just have to use the first code snippet and then all the other stuff (like defining  the row layout.xml and the view holder pattern ) are going to be configured on the recycler view methods? Sorry if I am a little confusing for you, but I am relatively new to this and I cannot easily make the connection between the classic parse query adapter and this gist. If you ever have some time and will, it would be very helpful for me if you could share an empty structure of this gist with all the methods I should use and when inside the code. Nonetheless, thank you for the above snippet, I will try to figure it out!!

**Comment by msrowley** [comment]
@Ralphilius Never mind!! I figures it out. My mistake was that I was trying to modify the original gist rather than extending it to my custom class. Thank you again for your time and the code snippets above!!

**Comment by msrowley** [comment]
@wangmengyan95 I tried the above gist and it works really well for the basic adapter functionality but it misses crucial parsequeryadapter methods, that made development more easy and straightforward. So any news please from the official dev team on that matter??

**Comment by lukas1994** [comment]
see https://github.com/ParsePlatform/ParseUI-Android/pull/72
(it's not ready yet but we're working on it)

**Comment by msrowley** [comment]
@lukas1994 Thanks for updating the status!! I am watching for changes, as we really need it for our project! Keep up the good work!! Cheers.

**Comment by msrowley** [comment]
@lukas1994 I've seen that the development has stopped about a month ago. Is there a problem with the implementation or you have forked it somewhere else?? Will it be ready anytime soon, as it is needed to adopt the material design principles in our app?? Thank you again!!

**Comment by msrowley** [comment]
@wangmengyan95 How can I re-open the issue please, because it's been a long time now, and this should be a priority for the parse sdk, as for any app that wants to support the material design principles and widgets and be backwards compatible with older versions of android, it is a necessity to use the recycler view widget from the support library, something that parsequeryadapter doesn't support until today. I really cannot understand why it is not implemented yet. Are you aware of the latest android development news?? RecyclerView is out for at least one and a half year and the design support and AppCompat libraries which support the material design guidelines are at least out for half a year. As I stated in my op, Google suggests migration to RecyclerView not only for Lollipop(and now Marshmallow) , but for older versions too!! I would like to hear from you please.

**Comment by msrowley** [comment]
@wangmengyan95 @lukas1994 As this is a paid sdk, and there is no profound way to access parse support other than github, could you at least give an answer and show some care for your customers??

**Comment by Ralphilius** [comment]
@msrowley Actually they have built it but not tested/merged it to master brand yet. You can check this pull request for more information: https://github.com/ParsePlatform/ParseUI-Android/pull/72

If you want, you can use the ParseQueryAdapter code in that pull. I have adapted and tailored it to use with a custom layout.

Cheers,

**Comment by wangmengyan95** [comment]
@msrowley @Ralphilius, we are working on open source ParseUI(probably we will do it this week) so before that we want to keep master as stable as possible. After that, we will start to handle this PR. It seems Lukas do not actively maintain his PR so I wil take over it.

**Comment by Ralphilius** [comment]
@wangmengyan95 Thanks. Please make it easy to use custom layout too. I have tried to adjust current PR to allow this.

**Comment by msrowley** [comment]
@wangmengyan95 Thank you for sharing information on this matter. Hope to implement it soon. Please keep us posted here on the progression. Have a nice weekend!!

**Comment by msrowley** [comment]
@wangmengyan95 Hello there. Any news on the development of ParseQueryAdapter for RecyclerView please??

**Comment by juicycleff** [comment]
Waiting for the QueryAdapter for RecyclerView to no avail. I wonder why its taking Parse so long have it out. Using RecyclerView in my project with the Parse SDK has been a bit cumbersome, Sometimes making me feel ike we should have used the old plain REST API

**Comment by msrowley** [comment]
@wangmengyan95 Any answer please?? Should we change platform?? At least keep us informed. Lack of professionalism? Why you continue to mark it as closed??

**Comment by juicycleff** [comment]
Please I would like someone to help point me in the right direction with using the ParseRecyclerQueryAdapter. I'm trying to retrieve articles with my current adapter class that implements the standard RecyclerView. my implementation of pagination is not working properly soIi would like a demonstration from anyone that has used the ParseRecyclerQueryAdapter to achieve the following. By translating it from me so I get the implementation.

public class ArticleRVAdapter extends RecyclerView.Adapter<ArticleRVAdapter.ArticleViewHolder> {
    //creating alist and making it empty
    List<Article> articleData = Collections.emptyList();

    private LayoutInflater inflater;
    private Context context;

    private int lastAnimatedPosition = -1;
    private int itemsCount = 0;
    private static final int ANIMATED_ITEMS_COUNT = 2;

    public ArticleRVAdapter(Context context, List<Article> data){
        inflater=LayoutInflater.from(context);
        this.articleData= data;
        this.context = context;
    }

    @Override
    public ArticleViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {

        View view = inflater.inflate(R.layout.article_item, parent, false);
        ArticleViewHolder viewHolder = new ArticleViewHolder(view);
        return viewHolder;
    }

    private void runEnterAnimation(View view, int position) {
        if (position >= ANIMATED_ITEMS_COUNT - 1) {
            return;
        }

        if (position > lastAnimatedPosition) {
            lastAnimatedPosition = position;
            view.setTranslationY(com.boldsofts.copmobile.util.Utils.getScreenHeight(context));
            view.animate()
                    .translationY(0)
                    .setInterpolator(new DecelerateInterpolator(3.f))
                    .setDuration(700)
                    .start();
        }
    }

    @Override
    public void onBindViewHolder(ArticleViewHolder holder, int position) {
        //runEnterAnimation(holder.itemView, position);
        Article current = articleData.get(position);
        //holder.headImage.setImageBitmap(current.getArticleImage());
        holder.author.setText(current.getArticleTitle());
        holder.title.setText(current.getArticleTitle());
        holder.body.setText(current.getArticleBody());
        holder.author.setText(current.getArticleAuthor());
        holder.dateCreated = current.getDateCreated();
        holder.headImage.setImageBitmap(current.getArticleImage());
        holder.objectId = (current.getObjectId());

        //holder.s
        //holder.dateCreated.setText(current.getDateCreated());
    }

    public void animateTo(List<Article> models) {
        applyAndAnimateRemovals(models);
        applyAndAnimateAdditions(models);
        applyAndAnimateMovedItems(models);
    }

    private void applyAndAnimateRemovals(List<Article> newModels) {
        for (int i = articleData.size() - 1; i >= 0; i--) {
            final Article model = articleData.get(i);
            if (!newModels.contains(model)) {
                removeItem(i);
            }
        }
    }

    private void applyAndAnimateAdditions(List<Article> newModels) {
        for (int i = 0, count = newModels.size(); i < count; i++) {
            final Article model = newModels.get(i);
            if (!articleData.contains(model)) {
                addItem(i, model);
            }
        }
    }

    private void applyAndAnimateMovedItems(List<Article> newModels) {
        for (int toPosition = newModels.size() - 1; toPosition >= 0; toPosition--) {
            final Article model = newModels.get(toPosition);
            final int fromPosition = articleData.indexOf(model);
            if (fromPosition >= 0 && fromPosition != toPosition) {
                moveItem(fromPosition, toPosition);
            }
        }
    }

    public void addItem(int position, Article data) {
        articleData.add(position, data);
        notifyItemInserted(position);
    }

    public void removeItem(int position) {
        articleData.remove(position);
        notifyItemRemoved(position);
    }

    public void moveItem(int fromPosition, int toPosition) {
        final Article model = articleData.remove(fromPosition);
        articleData.add(toPosition, model);
        notifyItemMoved(fromPosition, toPosition);
    }

    // New add logic
    public void add(Article article) {
        insert(article, articleData.size());
    }

    public void insert(Article article, int position) {
        articleData.add(position, article);
        notifyItemInserted(position);
    }

    public void remove(int position) {
        articleData.remove(position);
        notifyItemRemoved(position);
    }

    public void clear() {
        int size = articleData.size();
        articleData.clear();
        notifyItemRangeRemoved(0, size);
    }

    public void addAll(List<Article> articles) {
        int startIndex = articleData.size();
        articleData.addAll(startIndex, articles);
        notifyItemRangeInserted(startIndex, articles.size() - 1);
    }

    /**
     * Returns the total number of items in the data set hold by the adapter.
     *
     * @return The total number of items in this adapter.
     */
    @Override
    public int getItemCount() {
        return articleData.size();
    }

    public class ArticleViewHolder extends RecyclerView.ViewHolder
            implements View.OnClickListener {

        CardView cardView;
        TextView title;
        TextView body;
        Date dateCreated;
        TextView author;
        ImageView headImage;
        String objectId;

        public ArticleViewHolder(final View itemView) {
            super(itemView);
            itemView.setClickable(true);
            itemView.setLongClickable(true);
            itemView.setOnClickListener(this);


            cardView = (CardView) itemView.findViewById(R.id.card_article);
            title = (TextView) itemView.findViewById(R.id.text_title);
            body = (TextView) itemView.findViewById(R.id.text_article_body);
            //dateCreated = itemView.findViewById(R.id.text_article_body);
            author = (TextView) itemView.findViewById(R.id.text_author);
            headImage = (ImageView) itemView.findViewById(R.id.imageView_thumb);


        }
        @Override
        public void onClick(View v) {
            Intent intent = new Intent(v.getContext(), ArticleInformationActivity.class);
            intent.putExtra("article_id", articleData.get(getLayoutPosition()).getObjectId());
            intent.putExtra("article_title", articleData.get(getLayoutPosition()).getArticleTitle());
            intent.putExtra("article_body", articleData.get(getLayoutPosition()).getArticleBody());
            intent.putExtra("article_author", articleData.get(getLayoutPosition()).getArticleAuthor());
            intent.putExtra("article_date", articleData.get(getLayoutPosition()).getDateCreated());
            v.getContext().startActivity(intent);

        }
    }
}

**Comment by siqtedar** [comment]
Dear wangmengyan95,
Is there any update on the development of ParseQueryRecyclerViewAdapter? I want to use it in my code. When would you merge it in the master? Is it expected soon?
Best!

**Comment by siqtedar** [comment]
Can anyone please guide me on how to use custom layout with this adapter (#72)? It works for the default case but I am unable to use it with custom layout. Please provide a sample for this.

**Comment by jorgecasariego** [comment]
@siqtedar this can help you

[Stackoverflow](http://stackoverflow.com/a/34603652/2091181)

If you have any doubt just tell me

**Comment by spectrumIG** [comment]
This issue is marked as closed and I'm wondering why since there's no component merged and the PR is still stucked. I'm not a paid Parse user so...ok, i will accept this situation but, if this is the treatment reserved to customers too...well, I'm not going to be one for sure and i will not talk well about Parse support.This is not something trivial. It's a part of standard Android design pattern since Lollipop release. Very few people are still using ListAdapter as far as i know.

**Comment by arturwest** [comment]
Hi to all! I have done an example of recycler view adapter for parse with pagination https://github.com/arturwest/RecyclerParseQueryAdapter
