### ISSUE TITLE
Proposal for split ParseLoginUI moudle

### ISSUE THREAD

**Issue by wangmengyan95** [ParsePlatform/ParseUI-Android#66]
Since we add `ParseImageView` and `ParseQueryAdapter` to the repo, it make no sense to still keep them all in one login module.

We propose to split the `ParseLoginUI` into two modules. `ParseUI-Login` module for all login related classes. `ParseUI-Widget` module for `ParseImageView`, `ParseQueryAdapter` and future widgets.

For packaging, in `ParseUI-Login`, all classes are still under package `com.parse.ui` for backward compatibility.  In `ParseUI-Widget`, `ParseImageView` and `ParseQueryAdapter` are in `com.parse`, the future widgets will be in `com.parse.widget`.

Check PR #65 for details.

Please leave you opinions, suggestions or any thoughts under this issue.

Thanks.

**Comment by albertvilacalvo** [comment]
It makes sense. I just want to use ParseQueryAdapater.

**Comment by wangmengyan95** [comment]
#65
