### ISSUE TITLE
Facebook login error

### ISSUE THREAD

**Issue by flamoedo** [ParsePlatform/ParseUI-Android#74]
When i try to login to facebook, it returns a facebook error screen, that says:

Sorry, something went wrong.

We're working on it and we'll get it fixed as soon sa we can.

**Comment by wangmengyan95** [comment]
Hi @flamoedo , could you provide us some details information about how to repo this issue? In your description, it seems something wrong with your Facebook SDK. Could you tell us which Facebook SDK version you are using and the stacktrace of the exception. Thanks.

**Comment by flamoedo** [comment]
HI, wangmengyan95, this happens when you follow the quick guide, for android app registration.
The problem is that you write the hash code of your app, in the configuration page, but it does not get saved. Then, when you try to run the app and login to Facebook, the error page appears.
If you follow the links on the left menu for configuring your app the values are correctly saved, and the error does not happens.
