### ISSUE TITLE
ParseQueryAdapter crashed when local datastore is enabled

### ISSUE THREAD

**Issue by kwinto93** [ParsePlatform/ParseUI-Android#75]
Hello,
changes made in [commit](https://github.com/ParsePlatform/ParseUI-Android/commit/48cd2e5ba9ae76eaefa196dadfae7ec3893a9b36)
in file: `ParseQueryAdapter` and line: `393`, causes crash if local datastore is enabled.

I think in this line is missing something like this:
```
if (!Parse.isLocalDatastoreEnabled())
...
```
Best regards,
Matthew

**Comment by kwinto93** [comment]
Please `Lukas` check if there is the only line where it should be added.

**Comment by wangmengyan95** [comment]
@kwinto93 nice catch, I will send a PR and update test to cover this cases.

**Comment by wangmengyan95** [comment]
#76
