### ISSUE TITLE
Importing Parse-UI

### ISSUE THREAD

**Issue by 42geek** [ParsePlatform/ParseUI-Android#77]
Hi. 

I'm trying to import ParseUI as explained in this repository but I keep getting the following error: 

"Error:(5, 0) Cannot get property 'facebookSDK' on extra properties extension as it does not exist Open File"

any idea? TNX

**Comment by wangmengyan95** [comment]
Hi @42geek, it seems you do not config your facebookSDK path correctly. Could you please paster your app's build.gralde?

**Comment by wangmengyan95** [comment]
Close for no further information, feel free to reopen it.
