### ISSUE TITLE
Add specific listener for signup event

### ISSUE THREAD

**Issue by slpereira** [ParsePlatform/ParseUI-Android#79]
My suggestion is create a specific listener to propagate signup events. In the current implementation, the signup event is propagated through the login listener, so, you cannot distinguish from signup and login event. In my case, I need special processing when the user signup to my application. If a specific listener is created to propagate signup events, users of the LoginUI API can receive this event in a specific channel and react as they want.

**Comment by wangbourne** [comment]
+1. 
This will be very useful when an special alert view needs to show after sign up or sign in. For example:
sign up : You have successfully created a new account.
sign in : You have successfully sign in.
