### ISSUE TITLE
How to disable signup button?

### ISSUE THREAD

**Issue by cshlxm** [ParsePlatform/ParseUI-Android#85]
I configured my login layout from com_parse_ui-parse_fragment.xml, when I delete the signup button,the login will not work,and debug log will display Layout missing signup button Disabled username/password login and signup because of missing layout elements.

**Comment by Ralphilius** [comment]
Use `View.GONE` instead?

**Comment by wangmengyan95** [comment]
You can just add `android:visibility="gone"` to the button like this
```xml
<Button
    android:id="@+id/parse_signup_button"
    style="@style/ParseLoginUI.Button"
    android:layout_marginLeft="@dimen/com_parse_ui_small_horizontal_spacing"
    android:layout_weight="0.5"
    android:text="@string/com_parse_ui_parse_signup_button_label"
    android:visibility="gone"/>
```
